### ISSUE TITLE
Add more versatility to tanks

### ISSUE THREAD

**Issue by Taeko-ar** [benbenlaw/Casting#1]
Hi! I'm liking the mod but I think it lacks some QoL features:

- Being able to use tanks from other mods: Adding this would help with automation between mods, being able to make the smelting process smooth

- Stack tanks: As same as above, makes refilling the tanks less frequent if automated :) (Plus it helps with aesthetics) 

Adding any of those would be awesome (and implementing the first one maybe the 2nd one is not needed :p)

Thanks!

**Comment by benbenlaw** [comment]
hmm i think i get what you mean but i like having the tanks from the mod working with the blocks, in automation the controller outputs automatically to near by blocks as well eg controller to mixer/ solidifier
